[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pysbr"
version = "0.0.0"
dependencies = [
  "gql[all]",
  "fake-useragent",
  "pandas",
  "pytz",
  "PyYAML"
]


[tool.setuptools.packages.find]
where = ["."]
include = ["pysbr*"]
